controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_end_effector_controller
    type: $(arg execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home

  []